name: Build sing-box rule-sets
on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout geo
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/geo
          path: geo

      - name: Checkout sing-box
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          path: sing-box

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Build geo
        run: |
          cd geo
          go install ./cmd/geo
          geo

      - name: Build sing-box
        run: |
          cd sing-box
          make install
          sing-box

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/v2ray-rules-dat
          path: rules
          ref: release

      - name: Convert geo{ip,site}.dat
        run: |
          geo convert rules/geoip.dat -i v2ray -o sing -f geoip.db
          geo convert rules/geosite.dat -i v2ray -o sing -f geosite.db
