name: Build sing-box rule-sets
on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout geo
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/geo
          path: geo

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geo/go.mod
          cache-dependency-path: geo/go.sum

      - name: Install geo
        run: |
          cd geo && go install -v ./cmd/geo

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
          sing-box

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/v2ray-rules-dat
          path: dat
          ref: release

      - name: Build geo{ip,site}.dat
        run: |
          geo convert ip -i v2ray -o sing -f rules/geoip.db dat/geoip.dat
          geo convert site -i v2ray -o sing -f rules/geosite.db dat/geosite.dat

      - name: Commit and tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git status --porcelain; then exit 1; fi
          git add .
          git commit -m "Update rules"
          git tag "$(date +%Y-%m-%dT%H:%M:%S)"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          tags: true
