name: Build sing-box rule-sets
on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install geo
        run: |
          go install -v github.com/metacubex/geo/cmd/geo@master
          geo

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
          sing-box

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/v2ray-rules-dat
          path: rules
          ref: release

      - name: Convert geo{ip,site}.dat
        run: |
          geo convert rules/geoip.dat -i v2ray -o sing -f geoip.db
          geo convert rules/geosite.dat -i v2ray -o sing -f geosite.db
