name: Build sing-box rule-sets
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Variables
        run: |
          echo "TAG=$(env TZ=Asia/Shanghai date +%Y%m%d%H%M)" >>$GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Rules
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/v2ray-rules-dat
          path: dat
          ref: release

      - name: Download clash config
        env:
          CLASH_URL: ${{ secrets.CLASH_URL }}
        run: curl -fsSL "$CLASH_URL" >dat/clash-config.yaml

      - name: Preflight
        run: ./preflight.sh

      - name: Checkout geo
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/geo
          path: geo

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geo/go.mod
          cache-dependency-path: geo/go.sum

      - name: Install geo
        run: |
          cd geo && go install -v ./cmd/geo
          geo | head -1

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
          sing-box version

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Build config
        env:
          GITEE_USER: ${{ secrets.GITEE_USER }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          CLASH_URL: ${{ secrets.CLASH_URL }}
        run: ./build-sing-config.sh "$GITEE_USER" "$GITEE_TOKEN" "$CLASH_URL"

      - name: Build rule sets
        run: ./build-sing-rules.sh

      - name: Commit and Push
        run: ./commit-and-push.sh "Update rules" "${{ env.TAG }}"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: rules/*
