name: Build sing-box rule-sets
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Variable
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >>$GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout geo
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/geo
          path: geo

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geo/go.mod
          cache-dependency-path: geo/go.sum

      - name: Install geo
        run: |
          cd geo && go install -v ./cmd/geo

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
          sing-box version

      - name: Checkout Rules
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/v2ray-rules-dat
          path: dat
          ref: release

      - name: Check if rules have been changed
        run: |
          git -C dat rev-parse HEAD | tee output
          if diff output v2ray-rules-dat.commit; then
            echo "Upstream rules are not changed"
            exit 1
          else
            mv output v2ray-rules-dat.commit
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build geo{ip,site}.db and export rule sets
        run: |
          cd rules
          geo convert ip -i v2ray -o sing -f geoip.db ../dat/geoip.dat
          geo convert site -i v2ray -o sing -f geosite.db ../dat/geosite.dat
          rm -f *.json
          ../geo2sing.py

      - name: Download clash rules
        run: |
          mkdir -p clash
          cd clash
          ../clash-download.sh ../clash-list.txt

      - name: Merge clash rules
        run: |
          cd rules
          ../clash-merge.sh ../base
          ../clash-merge.sh ../clash 

      - name: Compile rule sets
        run: |
          cd rules
          rm -f *.srs
          ls -1 *.json | xargs -n1 sing-box rule-set compile

      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update rules"
          git tag "${{ env.TAG_NAME }}"
          git push --follow-tags

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: rules/*
