name: Build sing-box rule-sets
on:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout geo
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/geo
          path: geo

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geo/go.mod
          cache-dependency-path: geo/go.sum

      - name: Install geo
        run: |
          cd geo && go install -v ./cmd/geo

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
          sing-box

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Loyalsoldier/v2ray-rules-dat
          path: rules
          ref: release

      - name: Convert geo{ip,site}.dat
        run: |
          geo convert ip -i v2ray -o sing -f geoip.db rules/geoip.dat
          geo convert site -i v2ray -o sing -f geosite.db rules/geosite.dat
